title: John James Tomczak
description: Thanks for checking out my page, and hopefully then my work. Please do feel free to reach out.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

author: Some Person

# --- List of links in the navigation bar --- #
navbar-links:
About Me: "aboutme"
Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
Author's home: "https://deanattali.com"
