title: John James Tomczak
logo: /assets/img/my_face.jpeg
description: Thanks for checking out my page, and hopefully then my work. Please do feel free to reach out.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
