title: John James Tomczak
description: [Posts, on Substack](https://jjtposts.substack.com/people/1046252-john)
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

author: Some Person
